spring.application.name=trello-clone
spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:21370/railway
spring.datasource.username=root
spring.datasource.password=KrpsBOGclVawcHcsEGGQJEkrMOYURPQz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=${PORT:10000}
jwt.secret=trelloclone_super_secret_key_mahendra_2024
jwt.expiration=86400000