spring.application.name=trello-clone
spring.datasource.url=jdbc:mysql://localhost:3306/trello_clone
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
jwt.secret=trelloclone_super_secret_key_mahendra_2024
jwt.expiration=86400000