spring.application.name=trello-clone
spring.datasource.url=jdbc:mysql://bdzmoou46sqxfx0prs6r-mysql.services.clever-cloud.com:3306/bdzmoou46sqxfx0prs6r
spring.datasource.username=up1tn1xjmemtr9v9
spring.datasource.password=ZzovduXCYE1HytvyyXLA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=${PORT:10000}
jwt.secret=trelloclone_super_secret_key_mahendra_2024
jwt.expiration=86400000